config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "athletes#index"

  resources :athletes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  def view_sex
    if sex == 1
      "男"
    elsif sex == 2
      "女"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:name, :sex, :birth_date, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.slim
= form_for @athlete do |f|
  - if @athlete.errors.any?
    #error_explanation
      h2 = "#{pluralize(@athlete.errors.count, "error")} prohibited this athlete from being saved:"
      ul
        - @athlete.errors.full_messages.each do |message|
          li = message

  .form-group.row
    = f.label :name, "名前", { class: "col-sm-2 col-form-label" }
    .col-sm-6
      = f.text_field :name, class: "form-control"
  .form-group.row
    = f.label :sex, "性別", { class: "col-sm-2 col-form-label" }
    .col-sm-6
      = f.number_field :sex, class: "form-control"
  .form-group.row
    = f.label :birth_date, "生年月日", { class: "col-sm-2 col-form-label" }
    .col-sm-6
      = f.date_field :birth_date, class: "form-control"
  .form-group.row
    = f.label :note, "備考", { class: "col-sm-2 col-form-label" }
    .col-sm-6
      = f.text_area :note, size: "100x5", class: "form-control"
      
  .form-group.row
    .col-sm-10.offset-sm-2
      .actions = f.submit "更新", { class: "btn btn-danger" }

app/views/athletes/edit.html.slim
.row
  .col
    h1.my-5 近代五種 選手登録

    == render 'form'

    => link_to '詳細', @athlete
    '|
    =< link_to '戻る', athletes_path

app/views/athletes/index.html.slim
.row
  .col
    h1.my-5 近代五種 選手一覧

    table.table.table-bordered.table-striped
      thead.thead-dark
        tr
          th 名前
          th 性別
          th 生年月日
          th コメント
          th
      tbody
        - @athletes.each do |athlete|
          tr
            td = link_to athlete.name, athlete
            td = athlete.view_sex
            td = athlete.birth_date
            td = athlete.note
            td
              = link_to '編集', edit_athlete_path(athlete), { class: "btn btn-primary btn-sm" }
              | &nbsp;
              = link_to '削除', athlete, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-primary btn-sm"

    = link_to '新規登録', new_athlete_path, { class: "btn btn-primary" }

app/views/athletes/new.html.slim
.row
  .col
    h1.my-5 近代五種 選手登録

    == render 'form'

    = link_to '戻る', athletes_path

app/views/athletes/show.html.slim
p#notice = notice

p
  strong Name:
  = @athlete.name
p
  strong Sex:
  = @athlete.sex
p
  strong 生年月日:
  = @athlete.birth_date
p
  strong Note:
  = @athlete.note

=> link_to 'Edit', edit_athlete_path(@athlete)
'|
=< link_to 'Back', athletes_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    title
      | 近代五種

    = csrf_meta_tags
    = csp_meta_tag

    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"
    = stylesheet_link_tag    'application', media: 'all'
  body
    .container
      = yield

    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"
    = javascript_include_tag 'application'